audit_header: false
title: Bay Area Real Estate blog with Ed Karzai
description: Our mission at Karzai Real Estate Group is to be your best resource for San Jose real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Karzai Real Estate Group, your professional San Jose Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Ed Karzai
  title:
  license_number: 
  about_markdown: |
    Ed grew up in the Bay Area and knows each community. He graduated from San Jose State University with a degree in Engineering. After several years in the high-tech industry, he realized his real passion is helping people and thus became a Real Estate Professional. To Ed, Trust is earned not given. He has built his business through integrity and character. For sellers, Ed consistently sells his listings above market value. For buyers, Ed gets his offers accepted faster than most agents out there. Why? Because he knows the art of negotiation. If you would like to experience the difference, please call Ed today to set up a Free Consultation.
  brand: Karzai Real Estate Group
  brokerage: Keller Williams Realty San Jose Gateway
  market: San Jose
  address:
  phone: 408-893-6607
  phone_type:
  phone2:
  phone2_type:
  email: ekarzai@kw.com
  url: http://karzairealestategroup.com<br>CA DRE# 01801399

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.charmingsiliconvalleyhomes.com/sell/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.charmingsiliconvalleyhomes.com/results-map

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your San Jose Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.charmingsiliconvalleyhomes.com/sell/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a San Jose Home?"
    CTA_text2: "Search the entire MLS for your San Jose home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.charmingsiliconvalleyhomes.com/results-map

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/EdKarzaiBayAreaLiving/
  linkedin_url: https://www.linkedin.com/in/edkarzai/
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/ekarzai/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'San Jose Real Estate Podcast with Ed Karzai'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Jose Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Karzai Real Estate Group - your professional San Jose Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Jose, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Ed Karzai'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: Bay Area Real Estate blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
